spring:
  profiles:
    active: dev
---
server:
  port: 7001
# spring的配置
spring:
  profiles: dev
  application:
    name: springcloud-config-eureka
#Eureka配置
eureka:
  instance:
    #Eureka 服务端实例名称
    hostname: eureka7001.com
  client:
    #表示是否向Eureka注册中心注册自己
    register-with-eureka: false
    #为false表示自己为注册中心
    fetch-registry: false
    # 修改Eureka默认url
    service-url:
      defaultZone: http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/

---

server:
  port: 7001
# spring的配置
spring:
  profiles: test
  application:
    name: springcloud-config-eureka
#Eureka配置
eureka:
  instance:
    #Eureka 服务端实例名称
    hostname: eureka7001.com
  client:
    #表示是否向Eureka注册中心注册自己
    register-with-eureka: false
    #为false表示自己为注册中心
    fetch-registry: false
    # 修改Eureka默认url
    service-url:
      defaultZone: http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/

